### ISSUE TITLE
Support for "AutoLev" sensor from Substancia 3D

### ISSUE THREAD

**Issue by RPI-PMK** [mriscoc/Special_Configurations#1]
Hi,

I have an Autolev sensor from Substancia 3D and trying to get it working with your great firmware. Been using Manual Mesh for a while now and had no issues so far.

They use a modified Jyers firmware which they host on their site.

I have details of changes needed in Configuration.h and Configuration_adv.h but stuck as to how to make these changes to get it working. Can you please point me in the right direction ??

I got this from supplier. How would I implement this in firmware??

Configuration on Configuration.h
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define FIX_MOUNTED_PROBE
#define X_PROBE_OFFSET_FROM_EXTRUDER 0 // X offset: -left +right [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 0 // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0 // Z offset: -below +above [the nozzle]
#define AUTO_BED_LEVELING_BILINEAR
#define Z_SAFE_HOMING
#define MULTIPLE_PROBING 2
//#define MIN_SOFTWARE_ENDSTOP_Z
#define Z_CLEARANCE_DEPLOY_PROBE 3 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES 2 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE 2 // Z Clearance between multiple probes
//#define Z_AFTER_PROBING 5 // Z position after probing is done
#define Z_PROBE_LOW_POINT -2 // Farthest distance below the trigger-point to go
before stopping

Configuration on Configuration_adv.h
#define BABYSTEP_ZPROBE_OFFSET
#define DOUBLECLICK_FOR_Z_BABYSTEPPING

I have it installed on ender 3v2 and can measure the offsets but that is as far as I have got.

@mriscoc this was originally put on another of your repositories but suddenly closed and archived today. Is this something you can help me with.

Thanks

**Comment by mriscoc** [comment]
OK, the configurations that they provided are for an old Marlin version. I'm now generating the current configuration files and posting a release for you.

**Comment by mriscoc** [comment]
Your release is ready, please test it and report.
https://github.com/mriscoc/Marlin_Configurations/releases/tag/20220216-AutoLev

**Comment by mriscoc** [comment]
Closing because no more feedback. You are welcome.

**Comment by RPI-PMK** [comment]
Sorry, I've been very busy with work and home so unable to test yet.

Should be able to in a few weeks. Should we keep this open or open a new
case once the result is known??

**Comment by mriscoc** [comment]
re-open by request.

**Comment by Tillerman6** [comment]
My printer stopping is apparently not related to your fine software. The
problem repeats with a straight marlin standard build and no CR / BL
touch.  Could be a bad power supply or heater cartridge- troubleshooting
now- only fails for long prints.  Keep up the good work!  I may be back
when I get this nailed down.

**Comment by mriscoc** [comment]
There is a known bug with THERMAL_PROTECTION_VARIANCE_MONITOR that produce random false thermal alerts, I will to update your special release with that feature disabled.

**Comment by mriscoc** [comment]
Your special release has been updated with that feature disabled, please re-download and flash the new version.

**Comment by RPI-PMK** [comment]
Sorry, very new to this.

I tried to download to test over the weekend but could not find the bin file but lots of other files and directories. What am I doing wrong???

**Comment by mriscoc** [comment]
Latest version here: https://github.com/mriscoc/Marlin_Configurations/releases/tag/AutoLev

**Comment by Nbrooks639** [comment]
Im still not really understanding what to do   Sent from Mail for Windows From: Miguel Risco-CastilloSent: Monday, March 7, 2022 12:11 AMTo: mriscoc/Marlin_ConfigurationsCc: Nbrooks639; ManualSubject: Re: [mriscoc/Marlin_Configurations] Support for "AutoLev" sensor from Substancia 3D (Issue #1) Latest version here: https://github.com/mriscoc/Marlin_Configurations/releases/tag/AutoLev—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by mriscoc** [comment]
Download the appropriate binary file for your board version from that page and flash it.
![image](https://user-images.githubusercontent.com/2745567/156975409-2b001c00-a95b-4b5e-9204-97aebbb8c93a.png)

**Comment by Nbrooks639** [comment]
No s1  Sent from Mail for Windows From: Miguel Risco-CastilloSent: Monday, March 7, 2022 12:49 AMTo: mriscoc/Marlin_ConfigurationsCc: Nbrooks639; ManualSubject: Re: [mriscoc/Marlin_Configurations] Support for "AutoLev" sensor from Substancia 3D (Issue #1) Download the appropriate binary file for your board version from that page and flash it.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
